spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: restaurant_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'